### ISSUE TITLE
Export constants for user consumption

### ISSUE THREAD

**Issue by Akkuma** [wonism/redux-segment-node#1]
It would be nice to export this directly to the user from the main file rather than `/redux-segment-node/constants`

**Comment by wonism** [comment]
You mean you want to import some constants from main file?
like,
```
export { EVENT_TYPE_IDENTIFY, EVENT_TYPE_GROUP, ... };
```

**Comment by wonism** [comment]
resolved with 200af98fc388d3e51f17f1fdf91e94bb4f477bde
